services:
  react-app:
    image: candul1507/react-app:latest
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints: [ node.role != manager ]
    ports:
      - "3000:3000"
    networks:
      - ms-network

  eureka-server:
    image: candul1507/eureka-server:latest
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints: [ node.role != manager ]
    networks:
      - ms-network
    environment:
      eureka.instance.prefer-ip-address: "true"
      SPRING.ZIPKIN.BASEURL: http://zipkin:9411/
      SPRING_APPLICATION_JSON: '{"eureka":{"client":{"serviceUrl":{"defaultZone":"http://eureka-server:8761/eureka"}}}}'
    depends_on:
      - config-server
    ports:
      - 8761:8761

  config-server:
    image: candul1507/config-server:latest
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints: [ node.role != manager ]
    networks:
      - ms-network
    environment:
      SPRING.ZIPKIN.BASEURL: http://zipkin:9411/
      SPRING_APPLICATION_JSON: '{"eureka":{"client":{"serviceUrl":{"defaultZone":"http://eureka-server:8761/eureka"}}}}'
    ports:
      - 8888:8888

  api-gateway:
    image: candul1507/api-gateway:latest
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints: [ node.role != manager ]
    depends_on:
      - config-server
      - eureka-server
      - customer-service
      - card-service
    networks:
      - ms-network
    environment:
      SPRING.ZIPKIN.BASEURL: http://zipkin:9411/
      SPRING_APPLICATION_JSON: '{"eureka":{"client":{"serviceUrl":{"defaultZone":"http://eureka-server:8761/eureka"}}}}'
    ports:
      - 9090:9090

  card-service:
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      placement:
        constraints: [ node.role != manager ]
    image: candul1507/card-service:latest
    depends_on:
      - eureka-server
      - config-server
      - database_server
      - zipkin
    networks:
      - ms-network
    environment:
      SPRING_APPLICATION_JSON: '{"eureka":{"client":{"serviceUrl":{"defaultZone":"http://eureka-server:8761/eureka"}}}}'
      SPRING.ZIPKIN.BASEURL: http://zipkin:9411/
      SPRING_CLOUD_CONFIG_URI: http://config-server:8888
    ports:
      - "8082-8083:8082"

  customer-service:
    image: candul1507/customer-service:latest
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints: [ node.role != manager ]
    depends_on:
      - config-server
      - eureka-server
      - database_server
      - zipkin
    networks:
      - ms-network
    environment:
      SPRING_APPLICATION_JSON: '{"eureka":{"client":{"serviceUrl":{"defaultZone":"http://eureka-server:8761/eureka"}}}}'
      SPRING.ZIPKIN.BASEURL: http://zipkin:9411/
      SPRING_CLOUD_CONFIG_URI: http://config-server:8888
    ports:
      - 8080:8080

  zipkin:
    image: openjdk:8-jre-alpine
    volumes:
      - ./zipkin-server-2.24.2-exec.jar:/app/app.jar
    command: [ "java", "-jar", "/app/app.jar" ]
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints: [ node.role != manager ]
    networks:
      - ms-network
    ports:
      - "9411:9411"

  database_server:
    image: mysql:latest
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints: [ node.role != manager ]
    environment:
      MYSQL_ROOT_PASSWORD: 12345
    networks:
      - ms-network
    volumes:
      - ./scripts/:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints: [ node.role != manager ]
    environment:
      PMA_HOST: database_server
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    networks:
      - ms-network
    ports:
      - 80:80

volumes:
  database_server:

networks:
  ms-network:
    external: true
